OUTPUT_BUTTON_TITLE = "تغيير مجلد الإخراح"
INPUT_BUTTON_TITLE = "اختيار الملف"
INPUT_DIALOG_TITLE = "اختيار الملف الصوتي"
SUBMIT_BUTTON =" بدءالتحويل"
MENU_BAR_FILE = "ملف"
MENU_BAR_FILE_SETTINGS = "الاعدادات"
MENU_BAR_FILE_NEW = "ملف جديد"
MENU_BAR_FILE_EXIT ="خروج"
MENU_BAR_HELP = "المساعدة"
MENU_BAR_ABOUT= "عن البرنامج"
ERROR_API_KEY = "برجاء اضافة المفتاح الخاص بموقع wit.ai واعادة المحاولة"

